name: Metrics

on:
  schedule:
    - cron: "0 0 * * *"   # roda todo dia 00:00 UTC
  workflow_dispatch:       # permite rodar manualmente

jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          user: joaogabrielvianna
          template: classic
          base: ""                        # não mostrar cards base
          filename: metrics.svg           # nome do arquivo gerado
          config_timezone: America/Sao_Paulo
          plugin_isocalendar: yes
          plugin_isocalendar_duration: full-year
